### ISSUE TITLE
maxLength on Text is not included when migrating

### ISSUE THREAD

**Issue by thygesteffensen** [EAVFW/EAVFW.Extensions.DynamicManifest#2]
```
"type": {
    "type": "Text"
},
```
gives a standard length of 100, changing it to
```
"type": {
    "maxLength": 200,
    "type": "Text"
},
```
will not update the Database with the new length.

**Comment by pksorensen** [comment]
This was fixed in one of the latest https://www.nuget.org/packages/EAVFW.Extensions.Manifest.SDK , specific maxlength was added to the migrations. Any other properties will need to be added also. Gonna close this one here as fixed in dependency project when generating migrations.sql
